Ingest resources and their relationships
JupiterOne/graph-wpengine pull request #8
Opened 2021-06-30 13:54 UTC by eXtremeX

This PR ingests all the resources and their relationships

**Ingested/relevant entities:**
- **Account** `{ type: 'wp_engine_account', class: 'Account' }`
- **Domain** `{ type: 'wp_engine_domain', class: 'Domain' }`
- **Install** `{ type: 'wp_engine_install', class: 'Application' }`
- **Site** `{ type: 'wp_engine_site', class: 'Host' }`
- **User** `{ type: 'wp_engine_user', class: 'User' }`

**Relationships:**
- `wp_engine_account` -> **HAS** -> `wp_engine_install`
- `wp_engine_account` -> **HAS** -> `wp_engine_site`
- `wp_engine_install` -> **HAS** -> `wp_engine_domain`
- `wp_engine_site` -> **HAS** -> `wp_engine_install`
- `wp_engine_user` -> **HAS** -> `wp_engine_account`

**The Graph:**
![image](https://user-images.githubusercontent.com/8009142/123971715-94e34980-d9ba-11eb-880f-3ba8358f2f4e.png)

Pinging @aiwilliams @austinkelleher @ndowmon @mknoedel

2021-07-02 13:19 UTC, austinkelleher requested changes
Looks awesome! Left some minor comments.

2021-07-02 13:19 UTC, austinkelleher commented on docs/jupiterone.md
> +1. Generate credentials
This could be in a separate PR, but we should improve the setup instructions. Here is an example: https://github.com/JupiterOne/graph-auth0/blob/master/docs/jupiterone.md#integration-walkthrough

2021-07-02 13:19 UTC, austinkelleher commented on src/steps/user/__snapshots__/converters.test.ts.snap
> +        "first_name": "John",
We should add `firstName` and `lastName` properties. I'm going to update the `User` class in the data-model to include these properties.

2021-07-02 13:19 UTC, austinkelleher commented on src/steps/installs/__snapshots__/converters.test.ts.snap
> +  "primaryDomain": "sample.primary-domain.com",
This is great. Can we also add a `domainName` property to match the data model? https://github.com/JupiterOne/data-model/blob/master/src/schemas/Domain.json#L12

2021-07-02 13:19 UTC, austinkelleher commented on src/steps/domains/__snapshots__/index.test.ts.snap
> +      "isMultistate": undefined,
I think this is a typo and is resulting in `isMultistate` being `undefined`. 

`isMultistate` -> `isMultisite`

And fix the converter/TypeScript typing

2021-07-02 13:19 UTC, austinkelleher commented on src/steps/domains/__snapshots__/index.test.ts.snap
> +      "active": true,
This property is automatically assigned by our SDK from the value of the `status` property. When the value of `status === 'active'`, we automatically assign `active` to `true`. I don't the same is happening for `false` today though.

What other statuses are there for `wp_engine_install`? I think we should consider manually assigning this property in the convertor like this:

```
active: data.status === 'active'
```

Here: https://github.com/JupiterOne/graph-wpengine/pull/8/files#diff-13a197391c67f51d0734494961a4ce62cd42e75a75c61492d0181b736ab088ceR19

2021-07-02 13:19 UTC, austinkelleher commented on src/steps/accounts/index.ts
> +          _class: RelationshipClass.HAS,
I think we should change this relationship class to `MANAGES`. I don't think a `User` **HAS** an `Account`, but rather is responsible for "managing" (`MANAGES`) it.

2021-07-05 13:46 UTC, RPGPH commented on src/steps/installs/__snapshots__/converters.test.ts.snap
> +  "primaryDomain": "sample.primary-domain.com",
Hi @austinkelleher, for the `Install` entity, I used the `Application` model which doesn't have a `domainName` field. Would you prefer it to use the `Domain` model instead?

2021-07-07 15:04 UTC, austinkelleher commented on src/steps/installs/__snapshots__/converters.test.ts.snap
> +  "primaryDomain": "sample.primary-domain.com",
Hey @RPGPH. Thanks for the response. Please dismiss my comment about `domainName`!

2021-07-08 13:58 UTC, austinkelleher approved these changes
Awesome work @RPGPH @eXtremeX! Thank you!

2021-07-08 13:58 UTC, merged